### ISSUE TITLE
你好，请问哪里可以看到这篇论文吗，跟我的idea一样，可是谷歌都搜不到，麻烦你了。

### ISSUE THREAD

**Issue by secularsee** [thunlp/StyleAttack#1]
开题想到的idea，一直没找到类似文章，碰巧在这里看到了，不知道还能不能继续做下去了，希望可以拜读一下作者的论文。

**Comment by Yangyi-Chen** [comment]
Hi, thanks for watching. 
Paper link: https://arxiv.org/abs/2110.07139
