### ISSUE TITLE
作者你好，想了解相关配置问题。

### ISSUE THREAD

**Issue by secularsee** [thunlp/StyleAttack#2]
对这篇论文很感兴趣，希望可以完美复现，冒昧打扰一下，想知道作者的pythorh版本和cuda以及cudnn版本，或者还有什么需要值得注意的，麻烦作者了。

**Comment by Yangyi-Chen** [comment]
Hello, 感谢关注！ 
CUDA version:11.0; PyTorch 版本>=1.7.1.  
这份工作主要是两部分，一部分是Transfer data 生成，这个可以直接参考原论文以及[代码](https://github.com/martiansideofthemoon/style-transfer-paraphrase)， 或者直接使用我们已经转换好的数据，在data/transfer文件夹下；  第二部分就是我们这边用于后门攻击和对抗攻击的实现，这部分我们的实现没有太多复杂的流程，理论上可以很容易复现； 
如果在复现过程中遇到问题，feel free to directly email me~: yangyichen6666@gmail.com

**Comment by secularsee** [comment]
> Hello, 感谢关注！ CUDA version:11.0; PyTorch 版本>=1.7.1. 这份工作主要是两部分，一部分是Transfer data 生成，这个可以直接参考原论文以及[代码](https://github.com/martiansideofthemoon/style-transfer-paraphrase)， 或者直接使用我们已经转换好的数据，在data/transfer文件夹下； 第二部分就是我们这边用于后门攻击和对抗攻击的实现，这部分我们的实现没有太多复杂的流程，理论上可以很容易复现； 如果在复现过程中遇到问题，feel free to directly email me~: [yangyichen6666@gmail.com](mailto:yangyichen6666@gmail.com)

**Comment by secularsee** [comment]
好的，非常感谢
