### ISSUE TITLE
风格转换数据是怎么生成的呢？

### ISSUE THREAD

**Issue by libing125** [thunlp/StyleAttack#3]
bible/sst-2/test.tsv 和 clean/sst-2/test.tsv 的句子数量似乎不一样？

**Comment by Yangyi-Chen** [comment]
你好，感谢关注； 
是的，我们使用[这份代码](https://github.com/martiansideofthemoon/style-transfer-paraphrase) 做句子变换的时候有部分转换会出现错误，因此在生成transfer dataset 的时候就丢弃了这部分数据。
