### ISSUE TITLE
Why is the length of the style-transfer-dataset different from the original dataset?

### ISSUE THREAD

**Issue by zhaishengfang** [thunlp/StyleAttack#5]
such as data/transfer/shakespeare/sst-2/test.tsv

**Comment by Yangyi-Chen** [comment]
Thanks for watching! 

The style transfer models may get NONE output, so the original sentences are removed from the transferred datasets. 

But, we have updated bible/ag and bible/sst-2, which is the style employed in our experiments. We just keep those sentences that can not be successfully transformed in the transferred datasets. So the length is consistent.

**Comment by zhaishengfang** [comment]
Thanks
